services:
  waf:
    networks:
      - app_network
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: waf
    ports:
      - "8080:80"
      - "8443:443"
    restart: always
    volumes:
    # fichier reverse-proxy Nginx
    - ./reverse-proxy/custom.conf:/etc/nginx/conf.d/custom.conf

     # Dossier frontend buildÃ©
    - frontend_dist:/usr/share/nginx/html

    #fichier de config ModSecurity
    - ./reverse-proxy/modsecurity.conf:/etc/nginx/modsecurity.conf

    # certificats SSL
    - ./reverse-proxy/certs:/etc/ssl/certs
    depends_on:
    - frontend
    - api-gateway

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    networks:
      - app_network
    env_file:
      - .env
    depends_on:
      - authservice
    restart: always

  dbwriter:
    build:
      context: ./dbwriter
      dockerfile: Dockerfile
    container_name: dbwriter
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
    networks:
      - app_network
    restart: always

  authservice:
    networks:
      - app_network
    build:
      context: ./authservice
      dockerfile: Dockerfile
    container_name: authservice
    volumes:
      - sqlite_data:/app/data:ro 
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - .env
    command: npm run build
    volumes:
      - frontend_dist:/app/frontend/dist
    networks:
      - app_network
    restart: "no"

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    env_file:
      - .env
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl 
      - vault_data:/vault/file
      - vault_keys:/vault/keys
      - ./vault/vault-init.sh:/vault/vault-init.sh
      - ./vault/vault-start.sh:/vault/vault-start.sh
    entrypoint: >
      sh -c "
        apk add --no-cache bash &&
        bash /vault/vault-start.sh
      "
    restart: always
    networks:
      - app_network
  
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    container_name: blockchain
    networks:
      - app_network
    volumes:
      - ./blockchain/content:/app/content


volumes:
  sqlite_data:
  vault_data:
  vault_keys:
  frontend_dist:

networks:
  app_network:
    driver: bridge


